name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cubehotels'

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
